/*
Introduction:
"This project aims to analyze sales data of beverages across various regions to
 uncover trends and optimize marketing strategies. By leveraging geographic and sales data,
 seek to identify key market segments, understand consumer preferences, 
 and enhance distribution channels for improved profitability."
 */



select * from beverage_sales_data ; 
select  count(*) as  total_columns
from  information_schema.columns
where  table_schema = 'bevrages_sales' and table_name = 'beverage_sales_data';

/* Problem Statements
1) Sales Analysis:
i) How do sales vary across different beverage categories?
ii) Which products contribute the most to overall sales?
iii) What is the trend of sales over time?
iv) What is Sales Variation Across Beverage Categories ?
*/


-- Total sales by beverage category
select category as Category , sum(order_qty) as Total_Sales
from beverage_sales_data 
group by Category;

-- Top 10 selling products
select product as ProductNames , sum(order_qty) as TotalSales
from beverage_sales_data 
group by ProductNames
order by TotalSales
limit 10;

-- Sales trend over time
select Trnsaction_Dates , sum(order_qty) as TotalSales
from beverage_sales_data
group by Trnsaction_Dates ;

-- Sales Variation Across Beverage Categories
select category , sum(mrp_unit_price * order_qty) as TotalSales
from beverage_sales_data
group by category;

/*2) Market Analysis:
i) Which countries and cities have the highest sales of beverage products?
ii) Are there any geographical trends in beverage consumption?
iii) How does pricing affect sales in different regions? 
iv) Count the number of entries for each country.
*/

-- Total sales by country
select country , sum(order_qty) as TotalSales
from beverage_sales_data 
group by country
order by TotalSales desc;

-- Total Sales by city
select cities , sum(order_qty) as Totalsales
from beverage_sales_data
group by cities
order by TotalSales desc;

-- Average sales price per unit by country
select country , avg(cost_per_unit) as AvgPrice
from beverage_sales_data
group by country;

-- Number of entries for each country
SELECT country , COUNT(*) AS TotalEntries
FROM beverage_sales_data
GROUP BY country;


/*3)Product Performance:
i) Which brands are the most popular among consumers?
ii) Do certain packaging types or sizes sell better than others?
iii) Are there any seasonal variations in product sales?
iv) Which of this products are contributing in overall sales?
*/

-- Top selling brands
select brand , sum(order_qty) as TotalSales
from beverage_sales_data
group by brand
order by TotalSales desc
limit 10;

-- Sales by Packaging Type
select packaging_type , sum(order_qty) as TotalSales
from beverage_sales_data
group by packaging_type ;

--  Seasonal variations in sales 
select Month(Trnsaction_Dates) as Month , sum(order_qty) as TotalSales
from beverage_sales_data
group by Month;

-- Top Contributing Products to Overall Sales
select product, SUM(mrp_unit_price * order_qty) AS TotalSales
from beverage_sales_data
group by  product
order by TotalSales DESC
limit 5;

/* 
4) Channel Analysis:
i) What are the most effective sales channels for beverage products?
ii) How does online sales compare to offline sales?
iii) Are there any emerging sales channels that are gaining traction?
*/

-- Sales by channel
select sales_channel , sum(order_qty) as TotalSales
from beverage_sales_data
group by sales_channel;

-- Comparison of online vs offline sales
select channel_type , sum(order_qty) as TotalSales
from beverage_sales_data
group by channel_type;


/*
5) Profitability Assessment:
i) What is the profit margin for each product?
ii) what is Profit Margin as per quantity wise ?
iii) How does the cost of goods sold (COGS) impact profitability?
*/

-- Profit margin calculation (assuming CostPrice is a column)
select product , (sum(mrp_unit_price) - sum(cost_per_unit)) as Profit
from beverage_sales_data
group by product;

-- Profit Margin quantity wise
select  product, (SUM(mrp_unit_price * order_qty) - SUM(cost_per_unit * order_qty)) as ProfitMargin
from beverage_sales_data
group by  product
order by ProfitMargin DESC;

-- Products with Loss
select product , sum(mrp_unit_price - cost_per_unit) as loss
from beverage_sales_data
group by product
having loss<0;  -- there is no loss


/*
6)Customer Behavior:
i)What are the preferences of customers in different regions?
ii) Identify the total revenue generated by each seller
iii)How do discounts impact sales?
*/

-- Regional sales preferences
select country , category,  sum(order_qty) as TotalSales
from beverage_sales_data 
group by country , category ;

-- Total Revenue by each Retailer
select retailer, SUM(mrp_unit_price * order_qty) AS TotalRevenue
from beverage_sales_data
group by retailer;

-- Impact on sales from discounts
select country,sum(order_qty - discount) Sales_After_Discount
from beverage_sales_data
group by country; 



/* Insights from the Project:
1)Geographic Analysis: The project reveals geographic trends in beverage consumption, 
highlighting areas of high demand and potential growth opportunities.
2)Product Preferences: Through sales data analysis, we've identified popular beverage brands and product variants,
enabling targeted marketing campaigns.
3)Distribution Optimization: By analyzing sales channels and geographic distribution, 
we've optimized supply chain logistics for efficient product delivery.
4)Seasonal Patterns: The project uncovers seasonal fluctuations in beverage sales,
 allowing for strategic inventory management and promotion planning.
5)Market Segmentation: Utilizing demographic and sales data, 
we've segmented markets based on consumer preferences, 
leading to tailored marketing strategies for different customer groups.
*/

